config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  get 'home/about'
  get '/search' => 'search#search'
  
  devise_for :users, controllers: {
    sessions:        "users/sessions",
    passwords:       "users/passwords",
    registrations:   "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member  do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :animes do
    resource :favorites, only: [:create, :destroy]
    resources :anime_comments, only: [:create, :destroy]
  end

  namespace :admins do
    resources :animes, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
  end

  # seedに変更の為、devise使用しない(admins側)
  # devise_for :admins, controllers: {
  #   sessions:        "admins/sessions",  #admins/sessionsはコントローラー名
  #   passwords:       "admins/password",  
  #   registrations:   "admins/registrations"  
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime_comment.rb
class AnimeComment < ApplicationRecord

  belongs_to :user
  belongs_to :anime

  validates :comment, presence: true

end

app/controllers/anime_comments_controller.rb
class AnimeCommentsController < ApplicationController
  before_action :authenticate_user! #ログインユーザーのみアクセスを許可

  def create
    @anime = Anime.find(params[:anime_id])
    @comment = @anime.anime_comments.build(anime_comment_params)
    @comment.user_id = current_user.id
    @comment.save
    @comments = @anime.anime_comments.order(created_at: :desc)
  end

  def destroy
    @anime = Anime.find(params[:anime_id]) #rails routes確認内容
    @comment = AnimeComment.find(params[:id]) #rails routes確認内容
    @comment.user_id = current_user.id
    @comment.destroy
    @comments = @anime.anime_comments.order(created_at: :desc)
  end

  private
  def anime_comment_params
    params.require(:anime_comment).permit(:comment, :user_id, :anime_id)
  end
end

app/helpers/anime_comments_helper.rb
module AnimeCommentsHelper
end

app/views/anime_comments/_form.html.erb
<%= form_with(model: [anime, comment], url: anime_anime_comments_path(anime), method: :post) do |f| %>
  <%= f.text_area :comment, class:"input-mysize" %>
  <p><%= f.submit "コメント投稿", class: "btn btn-primary" %></p>
<% end %>

app/views/anime_comments/_index.html.erb
<p class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><%= comments.count %>件コメント！  ...さらに表示</p><br />
<%# 常時、表示分 %>
<% comments.first(3).each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
      <div class="comment-box">
        <div class="comment-text">
          <p><%= link_to "#{comment.user.name}", user_path(comment.user.id) %></p>
          <div class="comment-entty">
            <p><%= comment.comment %></p>
            <% if comment.user == current_user %>
              <p>
                <%= link_to anime_anime_comment_path(anime.id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                  <span><i class="fas fa-trash fa-2x" style="color: black;"></i></span>
                <% end %>
                <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
              </p>
            <% else %>
              <p><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></p>
            <% end %>
          </div>
          <hr>
        </div>
      </div>
    </li>
  <% end %>
<% end %>
<%# ４件目以降のコメント内容 %>
<div class="collapse" id="collapseExample">
  <% comments.offset(3).each do |comment| %>
    <% unless comment.id.nil? %>
      <li class="comment-container">
        <div class="comment-box">
          <div class="comment-text">
            <p><%= link_to "#{comment.user.name}", user_path(comment.user.id) %></p>
            <div class="comment-entry">
              <p><%= comment.comment %></p>
              <% if comment.user == current_user %>
                <p>
                  <%= link_to anime_anime_comment_path(anime.id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                    <span><i class="fas fa-trash fa-2x" style="color: black;"></i></span>
                  <% end %>
                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
                </p>
              <% else %>
                <p><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></p>
              <% end %>
            </div>
            <hr>
          </div>
        </div>
      </li>
    <% end %>
  <% end %>
</div>

app/views/anime_comments/create.js.erb
$("#comments_area").html("<%= j(render 'anime_comments/index', { comments: @comments, anime: @comment.anime }) %>")
$(".comment-create").html("<%= j(render 'anime_comments/form', { comment: @comment, anime: @comment.anime }) %>")
$("textarea").val('')

app/views/anime_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'anime_comments/index', { comments: @comments, anime: @comment.anime }) %>")
$("textarea").val('')