config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  get 'home/about'
  get '/search' => 'search#search'
  
  devise_for :users, controllers: {
    sessions:        "users/sessions",
    passwords:       "users/passwords",
    registrations:   "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member  do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :animes do
    resource :favorites, only: [:create, :destroy]
    resources :anime_comments, only: [:create, :destroy]
  end

  namespace :admins do
    resources :animes, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
  end

  # seedに変更の為、devise使用しない(admins側)
  # devise_for :admins, controllers: {
  #   sessions:        "admins/sessions",  #admins/sessionsはコントローラー名
  #   passwords:       "admins/password",  
  #   registrations:   "admins/registrations"  
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @anime_column = params["search"]["anime_column"]
    @how = params["search"]["how"]
    @title_main = params["title_main"]
    @datas = search_for(@how, @anime_column, @title_main)
  end

  private
  def match(anime_column, title_main)
    if anime_column == 'title'
      Anime.where(title: title_main)
    elsif anime_column == 'main'
      Anime.where(main: title_main)
    else
      Anime.all
    end
  end

  def partical(anime_column, title_main)
    if anime_column == 'title'
      Anime.where("title LIKE ?", "%#{title_main}%")
    else anime_column == 'main'
      Anime.where("main LIKE ?", "%#{title_main}%")
    end
  end

  def search_for(how, anime_column, title_main)
    case how
      when 'match'
        match(anime_column, title_main)
      when 'partical'
        partical(anime_column, title_main)
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_search_form.html.erb
<!--
<%= form_tag(search_path, :method => 'get') do %>
  <%= text_field_tag :search %>
  <% submit_tag 'タイトル検索', :name => nil, class: 'btn btn-primary btn-sm' %>
<% end %>
-->


<div class="search-form">
  <%= form_tag(search_path, :method => 'get') do %>
    <%= select_tag 'search[anime_column]', options_for_select({"タイトル" => "title", "アニ名言" => "main"}) %>
    <%= select_tag 'search[how]', options_for_select({"キーワード" => "partical", "完全一致" => "match"}) %>
    <%= text_field_tag "title_main" %>
    <%= submit_tag '検索', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/search/search.html.erb
<div class="index-content">
  <div class="container">
  <h2>検索結果ページ</h2>
    <%= render 'search_form' %>
    <% @datas.each do |data| %>
    <div class="col-lg-4">
      <div class="l-wrapper">
        <article class="card">
          <div class="card__header">
            <h3 class="card__title"><%= data.title %></h3>
            <figure class="card__thumbnail">
              <%= attachment_image_tag data, :image, :fill, 350, 250, fallback: "no_image.jpg" %>
            </figure>
          </div>
          <div class="card__body">
            <p class="card__text"><%= data.main %></p>
          </div>
          <div class="card__footer">
            <p class="card__text"><%= link_to "詳細ページを見る", anime_path(data.id), class: "blue-button" %></p>
          </div>
        </article>
      </div>
    </div>
    <% end %>
  </div>
</div>