config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  get 'home/about'
  get '/search' => 'search#search'
  
  devise_for :users, controllers: {
    sessions:        "users/sessions",
    passwords:       "users/passwords",
    registrations:   "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member  do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :animes do
    resource :favorites, only: [:create, :destroy]
    resources :anime_comments, only: [:create, :destroy]
  end

  namespace :admins do
    resources :animes, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
  end

  # seedに変更の為、devise使用しない(admins側)
  # devise_for :admins, controllers: {
  #   sessions:        "admins/sessions",  #admins/sessionsはコントローラー名
  #   passwords:       "admins/password",  
  #   registrations:   "admins/registrations"  
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #パスワードの正確性を検証
        :registerable, #ユーザー登録や編集、削除
        :recoverable, #パスワードをリセット
        :rememberable, #ログイン情報を保存
        :validatable, #(emailのフォーマットなどのバリデーション)
        :omniauthable #sns認証

  attachment :my_photo
  has_many :animes, dependent: :destroy 
  has_many :anime_comments, dependent: :destroy
  has_many :favorites ,dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  validates :name, presence: true,length: { in: 1..40 }
  validates :email, uniqueness: true
  

  # フォローしているかどうかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  # フォローする時のメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  # フォロー外す時のメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  # データーベースから情報を探し、データーがなければ、作成する
  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'ゲストユーザー') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :if_not_admin

  def index
    @users = User.all.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_users_path
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーでログインしました！"
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @animes = @user.animes.order(updated_at: :desc).page(params[:page]).per(9)
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集しました！"
      redirect_to user_path(@user.id)
    else 
      render :edit
    end
  end

  def following # @userがフォローしているユーザー
    @user = User.find(params[:id])
    @users = @user.following
    render 'following'
  end

  def followers # @userをフォローしているユーザー
      @user = User.find(params[:id])
      @users = @user.followers
      render 'followers'
  end

  private
  def user_params
    params.require(:user).permit(:name, :my_introdution, :my_photo)
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%# フォローボタン %>
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if @user.id != current_user.id %>
  <div id="bbb">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <% f.submit "フォロー解除", class: "btn btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/error_user_edit', user: @user %>

<div class="container">
  <h2>ユーザー編集ページ</h2>
  <div class="row">
    <div class="col-xs-3">
      <%= form_for(@user) do |f| %>
      <div class="form-group has-icon">
          <%= f.label :名前 %> <br />
          <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
      </div>
      <div class="form-group has-icon">
        <%= f.label :自己紹介 %><br />
        <%= f.text_area :my_introdution, autofocus: true %>
      </div>
        <div class="form-group has-icon">
          <div class="user-edit-image">
            <%= attachment_image_tag @user, :my_photo, :fill, 100, 100, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
          </div>
          <label class="control-label sr-only" for="inputEmail">自己紹介写真</label>
          <%= f.attachment_field :my_photo, placeholder: "自己紹介写真", class: "user-edit-form" %>
        </div> 
        <%= f.submit "編集を保存", class: "btn btn-primary" %>
        <%= link_to "戻る", :back, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="col-md-12">
  <h2>フォロワーページ</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><p>名前</p></th>
          <th><p>写真</p></th>
          <th><p></p></th>
          <th><p></p></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= attachment_image_tag user, :my_photo, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
            <td><%=  %> 
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/following.html.erb
<div class="container">
  <div class="col-md-12">
  <h2>フォローページ</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><p>名前</p></th>
          <th><p>写真</p></th>
          <th><p></p></th>
          <th><p></p></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= attachment_image_tag user, :my_photo, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
            <td><%=  %> 
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<h2>ユーザー一覧</h2>
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th><p>名前</p></th>
          <th><p>紹介写真</p></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to"#{user.name}", user_path(user.id) %></td>
            <td><%= attachment_image_tag user, :my_photo, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class='p-top__paginate'><%= paginate(@users) %></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-md-12">
  <h2><%= "#{@user.name}さんのページ" %></h2><br />
    <div>
      <%= render "follow_form" %>
    </div>
    <div class="follow">
      <%= link_to following_user_path(@user) do %>
        <div id="following_count"><p style="color: black;"><%= @user.following.count %> フォロー</p></div>
      <% end %>
    </div>
    <div class="follower">
      <%= link_to followers_user_path(@user) do %>
        <div id="followers_count"><p style="color: black;"><%= @user.followers.count %> フォロワー</p></div>
      <% end %>
    </div>

    <div class="profile-container">
      <table class="table">
        <tbody>
          <tr>
            <th>紹介写真</th><td><%= attachment_image_tag @user, :my_photo, size:'100x100', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
          </tr>
          <tr>
            <th>名前</th><td><p class="profile-name"><%= @user.name %></p></td>
          </tr>
          <tr>
          <th>自己紹介</th><td><p class="my_introduction"><%= @user.my_introdution %></p></td>
          </tr>
          <tr>
          <% if @user.id == current_user.id %>
            <td>
              <%= link_to "編集ページ", edit_user_path(@user), class: "btn btn-success" %>
              <%= link_to "戻る", :back, class: "btn btn-default" %>
            </td>
          <% else %>
            <td>
              <%= link_to "戻る", :back, class: "btn btn-default" %>
            </td>
          <% end %> 
          </tr>
        </tbody>
      </table>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><p>投稿者名</p></th>
          <th><p>アニメタイトル</p></th>
          <th><p>アニ名言</p></th>
          <th><p>アニメ属性</p></th>
          <th><p>写真</p></th>
        </tr>
      </thead>
      <tbody>
        <% @animes.each do |anime| %>
          <tr>
            <td><%= anime.user.name %></td>
            <td><%= link_to"#{anime.title}", anime_path(anime.id)  %> 
            <td><%= anime.main %> 
            <td><%= anime.type_anime_i18n %></td>
            <td><%= attachment_image_tag anime, :image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class='p-top__paginate'><%= paginate(@animes) %></div>
  </div>
</div>