config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  get 'home/about'
  get '/search' => 'search#search'
  
  devise_for :users, controllers: {
    sessions:        "users/sessions",
    passwords:       "users/passwords",
    registrations:   "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member  do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :animes do
    resource :favorites, only: [:create, :destroy]
    resources :anime_comments, only: [:create, :destroy]
  end

  namespace :admins do
    resources :animes, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
  end

  # seedに変更の為、devise使用しない(admins側)
  # devise_for :admins, controllers: {
  #   sessions:        "admins/sessions",  #admins/sessionsはコントローラー名
  #   passwords:       "admins/password",  
  #   registrations:   "admins/registrations"  
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord

  belongs_to :user
  has_many :anime_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  enum type_anime: { boy: 0, girl: 1 }
  validates :title, presence: true, length: { in: 2..30}
  validates :main, presence: true, length: { in: 2..30}
  validates :subbody, presence: true, length: { maximum: 150 }
  validates :type_anime, presence: true

  def self.search(search)
    if search
      Anime.where(['title LIKE ?', "%#{search}%"])
    else
      Anime.all
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/admins/animes_controller.rb
class Admins::AnimesController < ApplicationController
  before_action :if_not_admin

  def index
    @users = User.order(updated_at: :desc).page(params[:page]).per(15)
    @animes = Anime.all
  end

  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy
    redirect_to admins_animes_path
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :authenticate_user!, except: [:index] #indexのみ非ログインでも、許可

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)
    @anime.user_id = current_user.id
    if @anime.save
      redirect_to animes_path, notice: "投稿が完了しました！"
    else
      render :new
    end
  end

  def index
    @animes = Anime.order(updated_at: :desc).page(params[:page]).per(9)
  end

  def show
    @anime = Anime.find(params[:id])
    @user = @anime.user 
    @comments = @anime.anime_comments.order(created_at: :desc)
    @comment = @anime.anime_comments.build
  end

  def edit
    @anime = Anime.find(params[:id])
    if @anime.user != current_user
      redirect_to animes_path, alert: '投稿者のみアクセスが可能です。'
    end
  end

  def update
    @anime = Anime.find(params[:id])
    if @anime.update(anime_params)
      redirect_to anime_path(@anime.id), notice: "投稿を編集しました！"
    else
      render "edit"
    end
  end

  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy
    redirect_to animes_path, notice: "投稿を削除しました！"
  end

  def search
    @animes = Anime.search(params[:search])
  end

  private
  def anime_params
    params.require(:anime).permit(:title, :main, :subbody, :image)
  end

end

app/helpers/admin/anime_helper.rb
module Admin::AnimeHelper
end

app/helpers/admins/animes_helper.rb
module Admins::AnimesHelper
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/views/animes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h2>アニ名言編集ページ</h2>
      <%= form_for(@anime) do |f| %>
      <%= render 'layouts/error_anime', anime: @anime %>
        <div class="field">
          <%= f.label :アニメタイトル %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "title" %>
        </div><br />
        <div class="field">
          <%= f.label :名言 %><br />
          <%= f.text_field :main, autofocus: true, autocomplete: "main" %>
        </div><br />
        <div class="field">
          <%= f.label :名言に選んだ理由 %><br />
          <%= f.text_area :subbody, autofocus: true, autocomplete: "subbody" %>
        </div><br />
        <div class="field">
          <p><%= attachment_image_tag @anime, :image, size: '500x300' %></p>
          <%= f.attachment_field :image %>
        </div><br />
        <div class="field">
          <%= f.submit "編集を保存", class: "btn btn-primary" %>
          <%= link_to "投稿を削除", anime_path(@anime.id), method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn btn-danger", style: 'color:#FFFFFF;' %>
          <%= link_to "戻る", :back, class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/animes/index.html.erb
<div class="index-content">
  <div class="container">
  <h2>投稿一覧ページ</h2>
  <%= render 'search/search_form' %>
  <% @animes.each do |anime| %>
    <div class="col-lg-4">
      <div class="l-wrapper">
        <article class="card">
          <div class="card__header">
            <h3 class="card__title"><%= anime.title %></h3>
            <figure class="card__thumbnail">
              <%= attachment_image_tag anime, :image, :fill, 350, 250, fallback: "no_image.jpg", size: '350x250' %>
            </figure>
          </div>
          <div class="card__body">
            <p class="card__text"><%= anime.main %></p>
          </div>
          <div class="card__footer">
            <p class="card__text"><%= link_to "詳細ページを見る", anime_path(anime.id), class: "blue-button" %></p>
          </div>
        </article>
      </div>
    </div>
  <% end %>
  </div>
</div>

<div class='p-top__paginate'><%= paginate(@animes) %></div> 

app/views/animes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h2>アニ名言投稿画面</h2><br />
      <%= form_for @anime do |f| %>
        <%= render 'layouts/error_anime', anime: @anime %>
        <div class="form-group">
          <%= f.label :アニメタイトル %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "title" %>
        </div>
        <div class="form-group">
          <%= f.label :名言 %><br />
          <%= f.text_field :main, autofocus: true, autocomplete: "main" %>
        </div>
        <div class="form-group">
          <%= f.label :名言に選んだ理由 %><br />
          <%= f.text_area :subbody, autofocus: true, autocomplete: "subbody" %>
        </div>
        <div class="form-group">
          <%= f.label :アニメ属性 %><br />
          <%= f.select :type_anime, Anime.type_animes_i18n.invert.to_a %>
        </div>
        <div class="form-group">
          <%= f.label :画像 %><br />
          <%= attachment_image_tag @anime, :image %>
          <%= f.attachment_field :image %>
        </div>
        <div class="field">
          <%= f.submit "新規投稿", class: "btn btn-primary active" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/animes/show.html.erb
<div class="container">
<h2 class="main"><%= @anime.main %></h2>
  <div id="favorite_heart<%= @anime.id %>">
    <%= render partial: 'favorites/favorite', locals: { anime: @anime } %>
  </div><br />
  <div class="row-md-12">
    <table class="table">
      <tr>
        <th><p>投稿者:</p><th>
        <td><p><%= link_to  "#{@anime.user.name}さんの投稿を見に行く", user_path(@user), data: {"turbolinks" => false} %></p></td>
      </tr>
      <tr>
        <th><p>アニメタイトル:</p><th>
        <td><p><%= @anime.title %></p></td>
      </tr>
      <tr>
        <th><p>アニ名言:</p><th>
        <td><p><%= @anime.main %></p></td>
      </tr>
      <tr>
        <th><p>名言に選んだ理由:</p><th>
        <td><p><%= @anime.subbody %></p></td>
      </tr>
      <tr>
        <th><p>アニメ属性:</p><th>
        <td><p><%= @anime.type_anime_i18n %></p></td>
      </tr>
      <tr>
        <th><p>画像:</p><th>
        <td><p><%= attachment_image_tag @anime, :image, :fill, 300, 300, fallback: "no_image.jpg", size: '300x300' %></p></td>
      </tr>
    </table>
    <% if current_user == @anime.user %>
      <%= link_to "投稿編集ページ", edit_anime_path(@anime.id), class: "btn btn-success" %>
      <%= link_to "戻る", :back, class: "btn btn-default" %>
    <% else %>
      <%= link_to "戻る", :back, class: "btn btn-default" %>
    <% end %><br />
    <h3 class="text-left title">コメント一覧</h3>
    <ul>
      <div id="comments_area">
        <%= render partial: 'anime_comments/index', locals: { comments: @comments, anime: @anime } %>
      </div>
    </ul>
    <span class="text-left">コメント投稿</span>
    <div class="comment-create">
      <%= render partial: 'anime_comments/form', locals: { comment: @comment, anime: @anime } %>
    </div>
  </div>
</div>